export const homeActionTypes = {
    SET_HOME_LOGO : 'SET_HOME_LOGO',
    SET_MAIN_VIDEO_URL : 'SET_MAIN_VIDEO_URL',
    SET_EXPLORE_TITLE : 'SET_EXPLORE_TITLE',
    SET_EXPLORE_CONTENT : 'SET_EXPLORE_CONTENT',
    SET_EXPLORE_BACKGROUND : 'SET_EXPLORE_BACKGROUND',
    SET_RESTURANT_CONTENT : 'SET_RESTURANT_CONTENT',
    SET_RESTURANT_IMAGE : 'SET_RESTURANT_IMAGE',
    SET_VENUE_CONTENT : 'SET_VENUE_CONTENT',
    SET_ALL_RESTURANT : 'SET_ALL_RESTURANT',
    SET_CLICK_RESTURANT : 'SET_CLICK_RESTURANT',
}